In [ ]:
import torch

torch.__version__


'2.4.1+cu118'

In [6]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
x = torch.rand(4, 2)
print(x)

tensor([[0.7786, 0.6056],
        [0.0793, 0.2915],
        [0.4715, 0.2496],
        [0.8051, 0.1176]])


In [9]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [10]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [11]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.7383,  0.4393,  0.6446,  0.4735],
        [-0.0682,  0.3860,  0.3605, -0.5574]])


In [13]:
print(x.size())

torch.Size([2, 4])


In [4]:
ft = torch.FloatTensor([1, 2, 3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
print(ft.short())
print(ft.int())
print(ft.long())


tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [6]:
print(ft.float())
print(ft.double())
print(ft.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [7]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)


tensor([1.1348])
1.1347845792770386
torch.float32


In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([1.1348], device='cuda:0')
tensor([2.1348], device='cuda:0')
tensor([2.1348], dtype=torch.float64)


In [3]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [4]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [5]:
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(t2.ndim)
print(t2.shape)
print(t2)



2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [7]:
t3 = torch.tensor([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]]])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [8]:
list_data = [ [10, 20], [30, 40] ]
tensor1 = torch.Tensor(list_data)
print(tensor1)
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")


tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [9]:
if torch.cuda.is_available():
    tensor1 = tensor1.to("cuda")
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cuda:0


In [10]:
import numpy as np

numpy_data = np.array(list_data)
tensor2 = torch.Tensor(numpy_data)
print(tensor2)
print(f"tensor type: {type(tensor2)}, tensor shape: {tensor2.shape}")
print(f"tensor dtype: {tensor2.dtype}, tensor device: {tensor2.device}")

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [11]:
numpy_data = np.array(list_data)
tensor2_1 = torch.from_numpy(numpy_data)
print(tensor2_1)
print(f"tensor type: {type(tensor2_1)}, tensor shape: {tensor2_1.shape}")
print(f"tensor dtype: {tensor2_1.dtype}, tensor device: {tensor2_1.device}")
tensor2_2 = torch.from_numpy(numpy_data).float()
print('====================================')
print(tensor2_2)
print(f"tensor type: {type(tensor2_2)}, tensor shape: {tensor2_2.shape}")
print(f"tensor dtype: {tensor2_2.dtype}, tensor device: {tensor2_2.device}")

tensor([[10, 20],
        [30, 40]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64, tensor device: cpu
tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [12]:
tensor3 = torch.rand(2, 2)
print(tensor3)
tensor4 = torch.randn(2, 2)
print(tensor4)

tensor([[0.5816, 0.9394],
        [0.6582, 0.8414]])
tensor([[-0.7620, -0.9752],
        [ 0.2458, -0.4029]])


In [13]:
tensor5 = torch.randn(2, 2)
print(tensor5)
numpy_from_tensor = tensor5.numpy()
print(numpy_from_tensor)

tensor([[ 0.9530, -1.6619],
        [ 0.8755, -0.4746]])
[[ 0.952975   -1.6619068 ]
 [ 0.8754651  -0.47456363]]


In [ ]:
# 텐서의 연산(Operations)
# 03/27
import math
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))


tensor([[-0.6400,  0.2863]])
tensor([[0.6400, 0.2863]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.2863]])


In [16]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[-0.6400,  0.2863]])
tensor(-0.6400)
tensor(0.2863)
tensor(-0.1768)
tensor(0.6550)
tensor(-0.1832)
tensor([1, 2, 3])


In [18]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.6948, 0.0662],
        [0.5785, 0.0442]])
torch.return_types.max(
values=tensor([0.6948, 0.0662]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([0.6948, 0.5785]),
indices=tensor([0, 0]))


In [19]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.6948, 0.0662],
        [0.5785, 0.0442]])
torch.return_types.min(
values=tensor([0.5785, 0.0442]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.0662, 0.0442]),
indices=tensor([1, 1]))


In [20]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.0054, 0.3172],
        [0.6372, 0.7413]])


In [21]:
print(x + y)
print(torch.add(x, y))

tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [22]:
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [23]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.0054, 0.3172],
        [0.6372, 0.7413]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [24]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])


In [25]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])


In [26]:
print(x)
print(y)
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])


In [27]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.6851, 0.5508],
        [0.7872, 0.7542]])
tensor([[0.6851, 0.5508],
        [0.7872, 0.7542]])


In [ ]:
# 텐서의 조작 (Indexing)
# 4/2 

import torch
import numpy as np

x = torch.Tensor([[1, 2],
                  [3, 4]])

print(x)
print(x[0,0])
print(x[0, 1])
print(x[1, 0])
print(x[1, 1])
print(x[:, 0])
print(x[:, 1])
print(x[0, :])
print(x[1, :])

tensor([[1., 2.],
        [3., 4.]])
tensor(1.)
tensor(2.)
tensor(3.)
tensor(4.)
tensor([1., 3.])
tensor([2., 4.])
tensor([1., 2.])
tensor([3., 4.])


In [ ]:
# view: 텐서의 크기(size)나 모양(shape)을 변경
x = torch.randn(4, 5)
print(x)
y = x.view(20)
print(y)

tensor([[ 1.0525,  0.7212, -1.0784, -0.1812,  1.0945],
        [ 0.9191, -0.0191, -1.1757, -1.0004, -0.4634],
        [-0.4962, -0.8839, -1.5726,  0.4425,  1.5942],
        [ 1.1077,  0.8708, -0.2892,  0.2818, -0.7783]])
tensor([ 1.0525,  0.7212, -1.0784, -0.1812,  1.0945,  0.9191, -0.0191, -1.1757,
        -1.0004, -0.4634, -0.4962, -0.8839, -1.5726,  0.4425,  1.5942,  1.1077,
         0.8708, -0.2892,  0.2818, -0.7783])


In [4]:
z = x.view(5, -1)
print(z)

tensor([[ 1.0525,  0.7212, -1.0784, -0.1812],
        [ 1.0945,  0.9191, -0.0191, -1.1757],
        [-1.0004, -0.4634, -0.4962, -0.8839],
        [-1.5726,  0.4425,  1.5942,  1.1077],
        [ 0.8708, -0.2892,  0.2818, -0.7783]])


In [6]:
# item: 텐서의 값이 단 하나라도 존재하면 숫자값을 얻음

x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)

tensor([0.0966])
0.0966269001364708
torch.float32


In [ ]:
# 스칼라값 하나만 존재해야 item() 사용가능
# x = torch.randn(2) 
x = torch.randn(1)
print(x.item())

-0.5077429413795471


In [9]:
# squeeze: 차원을 축소(제거)

tensor = torch.rand(1, 3, 3)

print(tensor)
print(tensor.shape)

tensor([[[0.5433, 0.2059, 0.7479],
         [0.7746, 0.5525, 0.7715],
         [0.9422, 0.7303, 0.5285]]])
torch.Size([1, 3, 3])


In [11]:
t = tensor.squeeze()
print(t)
print(t.shape)

tensor([[0.5433, 0.2059, 0.7479],
        [0.7746, 0.5525, 0.7715],
        [0.9422, 0.7303, 0.5285]])
torch.Size([3, 3])


In [12]:
#unsqueeze: 차원을 증가(생성)
t = torch.rand(3, 3)

print(tensor)
print(t.shape)


tensor([[[0.5433, 0.2059, 0.7479],
         [0.7746, 0.5525, 0.7715],
         [0.9422, 0.7303, 0.5285]]])
torch.Size([3, 3])


In [15]:
tensor = t.unsqueeze(dim=0)
print(tensor)
print(tensor.shape)

tensor([[[0.9695, 0.6432, 0.7342],
         [0.4161, 0.8461, 0.9590],
         [0.2215, 0.9821, 0.2509]]])
torch.Size([1, 3, 3])


In [16]:
tensor = t.unsqueeze(dim=2)
print(tensor)
print(tensor.shape)

tensor([[[0.9695],
         [0.6432],
         [0.7342]],

        [[0.4161],
         [0.8461],
         [0.9590]],

        [[0.2215],
         [0.9821],
         [0.2509]]])
torch.Size([3, 3, 1])


In [17]:
# stack: 텐서간 결합
x = torch.FloatTensor([1, 4])
print(x)

y = torch.FloatTensor([2, 5])
print(y)

z = torch.FloatTensor([3, 6])
print(z)

print(torch.stack([x, y, z]))


tensor([1., 4.])
tensor([2., 5.])
tensor([3., 6.])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [22]:
# cat: 텐서를 결합하는 메소드 
#       넘파이의 stack과 유사하지만 쌓을 dim이 존재해야함
#       해당 차원을 늘려준 후 결합
a = torch.randn(1, 3, 3)
print(a)

b = torch.randn(1, 3, 3)
print(b)

c = torch.cat((a, b), dim=0)
print(c)

print(c.size())
print(c.shape)

tensor([[[-1.1494, -0.5403,  0.6230],
         [ 0.7570,  1.2062,  0.2060],
         [ 0.8215, -0.7597,  0.2412]]])
tensor([[[ 0.1530,  0.6896,  1.7803],
         [-2.6192,  1.3526,  0.5202],
         [ 0.6061, -0.8432,  1.1345]]])
tensor([[[-1.1494, -0.5403,  0.6230],
         [ 0.7570,  1.2062,  0.2060],
         [ 0.8215, -0.7597,  0.2412]],

        [[ 0.1530,  0.6896,  1.7803],
         [-2.6192,  1.3526,  0.5202],
         [ 0.6061, -0.8432,  1.1345]]])
torch.Size([2, 3, 3])
torch.Size([2, 3, 3])


In [24]:
c = torch.cat((a, b), dim=1)
print(c)

print(c.size())

tensor([[[-1.1494, -0.5403,  0.6230],
         [ 0.7570,  1.2062,  0.2060],
         [ 0.8215, -0.7597,  0.2412],
         [ 0.1530,  0.6896,  1.7803],
         [-2.6192,  1.3526,  0.5202],
         [ 0.6061, -0.8432,  1.1345]]])
torch.Size([1, 6, 3])


In [25]:
c = torch.cat((a, b), dim=2)
print(c)

print(c.size())

tensor([[[-1.1494, -0.5403,  0.6230,  0.1530,  0.6896,  1.7803],
         [ 0.7570,  1.2062,  0.2060, -2.6192,  1.3526,  0.5202],
         [ 0.8215, -0.7597,  0.2412,  0.6061, -0.8432,  1.1345]]])
torch.Size([1, 3, 6])


In [23]:
# chunk: 텐서를 여러 개로 나눌 때 사용 (몇 개로 나눌것인가?)

tensor = torch.rand(3, 6)
print(tensor)

t1, t2, t3 = torch.chunk(tensor, 3, dim=1)

print(t1)
print(t2)
print(t3)

tensor([[0.5666, 0.4524, 0.2300, 0.9740, 0.6391, 0.1182],
        [0.9345, 0.1807, 0.4748, 0.4675, 0.9530, 0.2868],
        [0.5855, 0.5290, 0.3778, 0.3036, 0.3835, 0.7746]])
tensor([[0.5666, 0.4524],
        [0.9345, 0.1807],
        [0.5855, 0.5290]])
tensor([[0.2300, 0.9740],
        [0.4748, 0.4675],
        [0.3778, 0.3036]])
tensor([[0.6391, 0.1182],
        [0.9530, 0.2868],
        [0.3835, 0.7746]])


In [26]:
# split: chunk와 동일한 기능이지만 조금 다름 (텐서의 크기는 몇인가?)
tensor = torch.rand(3, 6)

t1, t2 = torch.split(tensor, 3, dim=1)
print(tensor)

print(t1)
print(t2)

tensor([[0.8338, 0.6042, 0.2825, 0.4363, 0.3924, 0.5608],
        [0.3814, 0.2920, 0.0531, 0.6373, 0.6482, 0.2342],
        [0.3822, 0.2561, 0.3942, 0.6059, 0.6606, 0.4612]])
tensor([[0.8338, 0.6042, 0.2825],
        [0.3814, 0.2920, 0.0531],
        [0.3822, 0.2561, 0.3942]])
tensor([[0.4363, 0.3924, 0.5608],
        [0.6373, 0.6482, 0.2342],
        [0.6059, 0.6606, 0.4612]])


In [28]:
# torch tensor(텐서)르 numpy araay(배열)로 변환 가능
#           numpy()
#           from_numpy()

a = torch.ones(7)
print(a)

b= a.numpy()
print(b)

tensor([1., 1., 1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1. 1. 1.]


In [29]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2. 2. 2.]


In [30]:
import numpy as np

a = np.ones(7)
b = torch.from_numpy(a)

np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2., 2., 2.], dtype=torch.float64)
