In [ ]:
import torch

torch.__version__


'2.4.1+cu118'

In [6]:
x = torch.empty(4, 2)
print(x)

tensor([[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]])


In [7]:
x = torch.rand(4, 2)
print(x)

tensor([[0.7786, 0.6056],
        [0.0793, 0.2915],
        [0.4715, 0.2496],
        [0.8051, 0.1176]])


In [9]:
x = torch.zeros(4, 2, dtype=torch.long)
print(x)

tensor([[0, 0],
        [0, 0],
        [0, 0],
        [0, 0]])


In [10]:
x = torch.tensor([3, 2.3])
print(x)

tensor([3.0000, 2.3000])


In [11]:
x = x.new_ones(2, 4, dtype=torch.double)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)


In [12]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.7383,  0.4393,  0.6446,  0.4735],
        [-0.0682,  0.3860,  0.3605, -0.5574]])


In [13]:
print(x.size())

torch.Size([2, 4])


In [4]:
ft = torch.FloatTensor([1, 2, 3])
print(ft)
print(ft.dtype)

tensor([1., 2., 3.])
torch.float32


In [ ]:
print(ft.short())
print(ft.int())
print(ft.long())


tensor([1, 2, 3], dtype=torch.int16)
tensor([1, 2, 3], dtype=torch.int32)
tensor([1, 2, 3])


In [6]:
print(ft.float())
print(ft.double())
print(ft.half())

tensor([1., 2., 3.])
tensor([1., 2., 3.], dtype=torch.float64)
tensor([1., 2., 3.], dtype=torch.float16)


In [7]:
x = torch.randn(1)
print(x)
print(x.item())
print(x.dtype)


tensor([1.1348])
1.1347845792770386
torch.float32


In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)
y = torch.ones_like(x, device=device)
print(y)
x = x.to(device)
print(x)
z = x + y
print(z)
print(z.to('cpu', torch.double))

cuda
tensor([1.], device='cuda:0')
tensor([1.1348], device='cuda:0')
tensor([2.1348], device='cuda:0')
tensor([2.1348], dtype=torch.float64)


In [3]:
t0 = torch.tensor(0)
print(t0.ndim)
print(t0.shape)
print(t0)

0
torch.Size([])
tensor(0)


In [4]:
t1 = torch.tensor([1, 2, 3])
print(t1.ndim)
print(t1.shape)
print(t1)

1
torch.Size([3])
tensor([1, 2, 3])


In [5]:
t2 = torch.tensor([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(t2.ndim)
print(t2.shape)
print(t2)



2
torch.Size([3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [7]:
t3 = torch.tensor([[[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]],
                   [[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]]])

print(t3.ndim)
print(t3.shape)
print(t3)

3
torch.Size([3, 3, 3])
tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])


In [8]:
list_data = [ [10, 20], [30, 40] ]
tensor1 = torch.Tensor(list_data)
print(tensor1)
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")


tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [9]:
if torch.cuda.is_available():
    tensor1 = tensor1.to("cuda")
print(f"tensor type: {type(tensor1)}, tensor shape: {tensor1.shape}")
print(f"tensor dtype: {tensor1.dtype}, tensor device: {tensor1.device}")

tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cuda:0


In [10]:
import numpy as np

numpy_data = np.array(list_data)
tensor2 = torch.Tensor(numpy_data)
print(tensor2)
print(f"tensor type: {type(tensor2)}, tensor shape: {tensor2.shape}")
print(f"tensor dtype: {tensor2.dtype}, tensor device: {tensor2.device}")

tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [11]:
numpy_data = np.array(list_data)
tensor2_1 = torch.from_numpy(numpy_data)
print(tensor2_1)
print(f"tensor type: {type(tensor2_1)}, tensor shape: {tensor2_1.shape}")
print(f"tensor dtype: {tensor2_1.dtype}, tensor device: {tensor2_1.device}")
tensor2_2 = torch.from_numpy(numpy_data).float()
print('====================================')
print(tensor2_2)
print(f"tensor type: {type(tensor2_2)}, tensor shape: {tensor2_2.shape}")
print(f"tensor dtype: {tensor2_2.dtype}, tensor device: {tensor2_2.device}")

tensor([[10, 20],
        [30, 40]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.int64, tensor device: cpu
tensor([[10., 20.],
        [30., 40.]])
tensor type: <class 'torch.Tensor'>, tensor shape: torch.Size([2, 2])
tensor dtype: torch.float32, tensor device: cpu


In [12]:
tensor3 = torch.rand(2, 2)
print(tensor3)
tensor4 = torch.randn(2, 2)
print(tensor4)

tensor([[0.5816, 0.9394],
        [0.6582, 0.8414]])
tensor([[-0.7620, -0.9752],
        [ 0.2458, -0.4029]])


In [13]:
tensor5 = torch.randn(2, 2)
print(tensor5)
numpy_from_tensor = tensor5.numpy()
print(numpy_from_tensor)

tensor([[ 0.9530, -1.6619],
        [ 0.8755, -0.4746]])
[[ 0.952975   -1.6619068 ]
 [ 0.8754651  -0.47456363]]


In [ ]:
# 텐서의 연산(Operations)
# 03/27
import math
a = torch.rand(1, 2) * 2 - 1
print(a)
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))


tensor([[-0.6400,  0.2863]])
tensor([[0.6400, 0.2863]])
tensor([[-0., 1.]])
tensor([[-1.,  0.]])
tensor([[-0.5000,  0.2863]])


In [16]:
print(a)
print(torch.min(a))
print(torch.max(a))
print(torch.mean(a))
print(torch.std(a))
print(torch.prod(a))
print(torch.unique(torch.tensor([1, 2, 3, 1, 2, 2])))

tensor([[-0.6400,  0.2863]])
tensor(-0.6400)
tensor(0.2863)
tensor(-0.1768)
tensor(0.6550)
tensor(-0.1832)
tensor([1, 2, 3])


In [18]:
x = torch.rand(2, 2)
print(x)
print(x.max(dim=0))
print(x.max(dim=1))

tensor([[0.6948, 0.0662],
        [0.5785, 0.0442]])
torch.return_types.max(
values=tensor([0.6948, 0.0662]),
indices=tensor([0, 0]))
torch.return_types.max(
values=tensor([0.6948, 0.5785]),
indices=tensor([0, 0]))


In [19]:
print(x)
print(x.min(dim=0))
print(x.min(dim=1))

tensor([[0.6948, 0.0662],
        [0.5785, 0.0442]])
torch.return_types.min(
values=tensor([0.5785, 0.0442]),
indices=tensor([1, 1]))
torch.return_types.min(
values=tensor([0.0662, 0.0442]),
indices=tensor([1, 1]))


In [20]:
x = torch.rand(2, 2)
print(x)
y = torch.rand(2, 2)
print(y)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.0054, 0.3172],
        [0.6372, 0.7413]])


In [21]:
print(x + y)
print(torch.add(x, y))

tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [22]:
result = torch.empty(2, 2)
torch.add(x, y, out=result)
print(result)

tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [23]:
print(x)
print(y)
y.add_(x)
print(y)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.0054, 0.3172],
        [0.6372, 0.7413]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])


In [24]:
print(x)
print(y)
print(x - y)
print(torch.sub(x, y))
print(x.sub(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])
tensor([[-0.0054, -0.3172],
        [-0.6372, -0.7413]])


In [25]:
print(x)
print(y)
print(x * y)
print(torch.mul(x, y))
print(x.mul(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])
tensor([[0.2419, 0.1650],
        [1.5342, 0.1831]])


In [26]:
print(x)
print(y)
print(x / y)
print(torch.div(x, y))
print(x.div(y))

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])
tensor([[0.9890, 0.4665],
        [0.6012, 0.2087]])


In [27]:
print(x)
print(y)
print(torch.matmul(x, y))
z = torch.mm(x, y)
print(z)

tensor([[0.4891, 0.2774],
        [0.9603, 0.1955]])
tensor([[0.4945, 0.5947],
        [1.5975, 0.9368]])
tensor([[0.6851, 0.5508],
        [0.7872, 0.7542]])
tensor([[0.6851, 0.5508],
        [0.7872, 0.7542]])
